### ISSUE TITLE
Slides: Iteration

### ISSUE THREAD

**Issue by augustopher** [uc-python/python-training-cincinnati-insurance#10]
Sources:

- [Intermediate class](https://github.com/uc-python/intermediate-python-datasci/blob/master/notebooks/03-Iteration.ipynb)
- [BANA 6043](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/book/06-module/lesson-6b.ipynb)

**Comment by augustopher** [comment]
@bradleyboehmke @eswan18 @cunningjames - I'm noticing some examples expanding concepts into pandas (e.g., iterating through a sequence ▶️ iterating through `DataFrame`/`Series`. Do we want to keep those previews, or move them into the "Intro to Pandas" sections (and make an explicit callback)?

Personally, I think this might be better to move into the pandas sections, and focus more on the core concepts here; though I'm not that set against it. Mostly wanted to get some discussion here before we get too far into adapting other sections.

**Comment by eswan18** [comment]
Yeah, I think I agree with you – iteration in Pandas isn't quite like iteration in the rest of the language, so I'd lean toward putting it in the Pandas section.
