### ISSUE TITLE
Bio Details

### ISSUE THREAD

**Issue by eswan18** [uc-python/python-training-cincinnati-insurance#14]
![image](https://user-images.githubusercontent.com/3449508/213918599-5b98ea9e-eeea-44c0-be23-4bd0c40b1ecd.png)

I'm adding bios in the intro section so I wanted to get some input from you all on basic details. Here's what my own looks like:
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/3449508/213918612-80a598cd-463b-463b-b16f-7fa863199f53.png">

So really what I need is:
- Headshot
- Job title
- A couple bullets about what you do, ideally things that will feel relevant to students
- Education
- Whatever links you want to share (only what you want)

**Comment by eswan18** [comment]
@bradleyboehmke – I have your education and links still but need your new title and description. @cunningjames & @augustopher, I'll need all of it from you two.

**Comment by bradleyboehmke** [comment]
@eswan18, following your pattern you can use this for me:

**Director, Data Science** at 84.51°

- Productionizing models and science solutions
- R&D and prototyping new solutions 
- Python, R, and MLOps toolchain

**Comment by augustopher** [comment]
![1516842255523](https://user-images.githubusercontent.com/32691115/213937575-eff8b8bb-36e9-42bf-98e3-9c36b3b73df8.jpeg)

**Lead Data Scientist** at 8451º

- Creating and maintaining data science tools for internal use
- Python, Bash (Shell), R

Academic

- BS, Chemistry, Thomas More College
- MS, Chemistry, University of Cincinnati
- MS, Business Analytics, University of Cincinnati

Contact

- GiHub: [augustopher](https://github.com/augustopher)
- LinkedIn: [August Powers](https://www.linkedin.com/in/august-powers-09717481/)
- Email: [guspowers0@gmail.com](mailto:guspowers0@gmail.com)

**Comment by cunningjames** [comment]
![79396E31-8045-4EB3-8732-E22F0C3EE264](https://user-images.githubusercontent.com/1495175/213954169-3c8e2a08-3871-4153-993c-6df83e6a0f2b.jpeg)

*Lead Data Scientist* at 8451º

* Researching and developing forecasting models
* Machine learning, Python

Education:

* BA, mathematics, University of Kentucky
* MA, economics, University of North Carolina (Greensboro)

Contact:
LinkedIn: [Jay Cunningham](https://www.linkedin.com/mwlite/in/jay-cunningham-60612886) 
Email: james@notbadafterall.com

**Comment by eswan18** [comment]
Thanks everybody!
