### ISSUE TITLE
Slides: Importing Data

### ISSUE THREAD

**Issue by jaycunningham-8451** [uc-python/python-training-cincinnati-insurance#18]
Sources:

* [Intro class](https://github.com/uc-python/intro-python-datasci/blob/master/notebooks/04-Importing-Data.ipynb)
* [BANA 6043](https://github.com/bradleyboehmke/uc-bana-6043/blob/main/book/02-module/lesson-2b.ipynb)

**Comment by jaycunningham-8451** [comment]
Oops, wrong login.

**Comment by cunningjames** [comment]
I've added proper slides. I also took the liberty of adding .DS_Store to .gitignore, so I don't have to worry about accidentally adding it to the repo.
