### ISSUE TITLE
Wish list: improve Makefile and slide generation

### ISSUE THREAD

**Issue by eswan18** [uc-python/python-training-cincinnati-insurance#34]
A couple things would be meaningful quality-of-life improvements:
- Make it correctly recognize dependencies so it knows to rebuild if a notebook has been changed (this doesn't seem to be working, I always have to run `make clean` first)
- Get proper mapping between dependencies and targets – modifying notebook 06 should only rebuild the 06 slides.
  - There is a directive to do this though I rarely see it: 
<img width="777" alt="image" src="https://user-images.githubusercontent.com/3449508/215008633-9ae7140e-beaf-4e45-b5d3-e348659a4f6f.png">
  - This is a little bit trickier than just writing the proper directive; all images need to be copied over to the slides directory if any have changed.

**Comment by eswan18** [comment]
This is low priority but I hope to come back to it when I have time.

**Comment by augustopher** [comment]
I _think_ I got a partial working solution - seems to work locally; however, it does not check for changes to the images. It also requires a small update to the bash script, which would change the manual invocation as well.

Updated `Makefile`:

```make
slides: $(wildcard slides/*.slides.html)

$(wildcard slides/*.slides.html): slides/%.slides.html: notebooks/%.ipynb
    bash scripts/generate_slides.sh $<

clean:
    rm -rf slides/
```

Updated `generate_slides.sh`:

```shell
#!/bin/bash

# same .git check as usual

cd notebooks
mkdir -p ../slides/images
cp -a ./images/* ../slides/images/

# make gives the 'notebooks/nb.ipynb' path, so strip it to the notebook name
FULL_NB_PATH="$1"
REL_NB=${FULL_NB_PATH//notebooks\//}

jupyter nbconvert --to slides $REL_NB_PATH --output-dir=../slides
```

This uses the static pattern rules, which I'm not familiar with at all.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/32691115/215223370-c133115c-5e25-4b2c-b7f2-7d5aa3f3fff3.png">

**Comment by augustopher** [comment]
I think the real wrinkle here is mapping the images to the slides; if we update an image, but don't update anything in that specific notebook, the notebook step won't run, even if we have a step that copies updated images.

**Comment by augustopher** [comment]
Okay, some further testing shows that it's not finding anything to run after doing `make clean`, so that's an issue. But I think the basic pattern is there, just need to add back in `slides/.finished` properly so it can catch that. I think that dependency can also be used for checking the images before running the slides generation.

**Comment by augustopher** [comment]
Messing with this again. I fixed the bug for no builds after `make clean`. Still working out how to incorporate updates to images; also, this still copies the images over for each updated notebook (can't get it to run just once without adding a directive just for images).

`Makefile`

```make
slides: html

NBFILES=$(wildcard notebooks/*-*.ipynb)
HTMLFILES=$(patsubst notebooks/%.ipynb,slides/%.slides.html,$(NBFILES))

html: $(HTMLFILES)

$(HTMLFILES): slides/%.slides.html: notebooks/%.ipynb
    bash scripts/generate_slides.sh $<

clean:
    rm -rf slides/
```

`scripts/generate_slides.sh`

```bash
#!/bin/bash

# existing git check

cd notebooks
mkdir -p ../slides/images/
cp -a ./images/* ../slides/images/

NB_PATH="$1"
REL_NB=${NB_PATH//notebooks\//}

jupyter nbconvert --to slides $REL_NB --output-dir=../slides
```

Also, not that we really need it for this repo, but the `html` step gives a template for how we could add other output builders, given some updates to the bash script arguments.
